In [2]:
import pandas as pd
# Load the csv file into DataFrame
df = pd.read_csv("social_capital_college.csv")
df.head()

,college,college_name,zip,county,mean_students_per_cohort,ec_own_ses_college,ec_own_ses_se_college,ec_parent_ses_college,ec_parent_ses_se_college,ec_high_own_ses_college,...,ec_high_parent_ses_se_college,exposure_own_ses_college,exposure_parent_ses_college,bias_own_ses_college,bias_parent_ses_college,bias_high_own_ses_college,bias_high_parent_ses_college,clustering_college,support_ratio_college,volunteering_rate_college
0,100200,Alabama A & M University,35762,1089,943.666667,0.85678,0.02233,0.67629,0.03241,1.12202,...,0.03498,0.84662,0.65090,-0.01200,-0.03900,-0.32529,-0.14036,0.24470,0.99483,0.03256
1,100300,Faulkner University,36109,1101,227.666667,1.30964,0.04869,1.26671,0.05812,1.54639,...,0.05134,1.23776,1.20183,-0.05807,-0.05398,-0.24935,-0.12001,0.40754,0.99481,0.03336
2,100400,University of Montevallo,35115,1117,494.000000,1.42378,0.03040,1.15413,0.03638,1.57365,...,0.03395,1.41664,1.17101,-0.00504,0.01442,-0.11083,-0.05979,0.30921,0.99683,0.09566
3,100500,Alabama State University,36104,1101,NaN,0.77916,0.01937,0.67090,0.03038,1.04811,...,0.03201,0.75162,0.65297,-0.03664,-0.02747,-0.39448,-0.12802,0.23222,0.99485,0.02150
4,100700,Central Alabama Community College,35010,1123,NaN,0.72742,0.03504,0.77238,0.04497,0.98888,...,0.04984,0.76579,0.76786,0.05010,-0.00589,-0.29133,-0.13139,0.34104,0.99271,0.02922

In [3]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2586 entries, 0 to 2585
Data columns (total 22 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   college                        2586 non-null   int64
 1   college_name                   2586 non-null   object
 2   zip                            2586 non-null   int64
 3   county                         2586 non-null   int64
 4   mean_students_per_cohort       2097 non-null   float64
 5   ec_own_ses_college             2362 non-null   float64
 6   ec_own_ses_se_college          2362 non-null   float64
 7   ec_parent_ses_college          2192 non-null   float64
 8   ec_parent_ses_se_college       2192 non-null   float64
 9   ec_high_own_ses_college        2362 non-null   float64
 10  ec_high_own_ses_se_college     2362 non-null   float64
 11  ec_high_parent_ses_college     2192 non-null   float64
 12  ec_high_parent_ses_se_college  2192 non-null   float64
 13  exposure_own_ses_college       2362 non-null   float64
 14  exposure_parent_ses_college    2192 non-null   float64
 15  bias_own_ses_college           2362 non-null   float64
 16  bias_parent_ses_college        2192 non-null   float64
 17  bias_high_own_ses_college      2362 non-null   float64
 18  bias_high_parent_ses_college   2192 non-null   float64
 19  clustering_college             2586 non-null   float64
 20  support_ratio_college          2586 non-null   float64
 21  volunteering_rate_college      2585 non-null   float64
dtypes: float64(18), int64(3), object(1)
memory usage: 444.6+ KB

,college,zip,county,mean_students_per_cohort,ec_own_ses_college,ec_own_ses_se_college,ec_parent_ses_college,ec_parent_ses_se_college,ec_high_own_ses_college,ec_high_own_ses_se_college,...,ec_high_parent_ses_se_college,exposure_own_ses_college,exposure_parent_ses_college,bias_own_ses_college,bias_parent_ses_college,bias_high_own_ses_college,bias_high_parent_ses_college,clustering_college,support_ratio_college,volunteering_rate_college
count,2.586000e+03,2586.000000,2586.000000,2097.000000,2362.000000,2362.000000,2192.000000,2192.000000,2362.000000,2362.000000,...,2192.000000,2362.000000,2192.000000,2362.000000,2192.000000,2362.000000,2192.000000,2586.000000,2586.000000,2585.000000
mean,6.107719e+05,47902.332560,29518.277649,1956.676284,1.357320,0.035058,1.116442,0.042669,1.511512,0.027923,...,0.040692,1.364535,1.126334,0.008823,0.010538,-0.126855,-0.068048,0.305540,0.974400,0.064852
std,8.256616e+05,29184.729688,15890.330345,4364.987592,0.367843,0.015284,0.301588,0.016333,0.319126,0.015200,...,0.016968,0.351307,0.295878,0.051413,0.041594,0.087313,0.051689,0.110333,0.045569,0.032701
min,1.002000e+05,603.000000,-2.000000,50.000000,0.216220,0.008950,0.272970,0.011020,0.335510,0.005130,...,0.008440,0.264870,0.290620,-0.156220,-0.164950,-0.834000,-0.335710,0.098910,0.516582,0.001441
25%,2.071250e+05,23621.000000,17038.500000,278.333333,1.100598,0.024103,0.881820,0.030820,1.326740,0.017263,...,0.028517,1.133610,0.896965,-0.019757,-0.012155,-0.167010,-0.094080,0.221562,0.972928,0.045000
50%,3.171000e+05,45784.000000,29510.000000,598.666667,1.446330,0.031650,1.140260,0.040030,1.595675,0.024625,...,0.037970,1.440680,1.139870,-0.002380,0.006600,-0.104165,-0.057865,0.281905,0.991430,0.058700
75%,5.531000e+05,72470.750000,42029.000000,1535.333333,1.662608,0.042600,1.362500,0.052552,1.768588,0.034955,...,0.051013,1.646257,1.361595,0.027208,0.029662,-0.066120,-0.030840,0.364437,0.997648,0.077110
max,4.283700e+06,99801.000000,78030.000000,26989.666667,1.901750,0.106770,1.731460,0.107740,1.934700,0.107090,...,0.104970,1.896580,1.718750,0.382230,0.244030,0.022520,0.097270,0.822496,1.000000,0.347065